{
 "title": "Logs",
 "description": "Raw logs for services",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "rpc_filter", "label": "RPC Filter" },
   { "name": "worker_filter", "label": "Worker Filter" },
   { "name": "spammer_filter", "label": "Spammer Filter" }
  ]
 },
 "panels": [
  {
   "title": "RPC",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"rpc\"}\n|~ \"(?i)${rpc_filter:regex}\"",
     "maxLines": 5000
    }
   ]
  },
  {
   "title": "Worker",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"worker\"}\n|~ \"(?i)${worker_filter:regex}\"",
     "maxLines": 5000
    }
   ]
  },
  {
   "title": "Spammer",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"spammer\"}\n|~ \"(?i)${spammer_filter:regex}\"",
     "maxLines": 5000
    }
   ]
  }
 ]
}